export const GET_CITY_DATA = 'GET_CITY_DATA'
export const GET_CITY_DATA_SUCCESS = 'GET_CITY_DATA_SUCCESS'
export const GET_CITY_DATA_FAILURE = 'GET_CITY_DATA_FAILURE'
export const SET_POSITION = 'SET_POSITION'
